### ISSUE TITLE
Decide on targets

### ISSUE THREAD

**Issue by biosfood** [TUMQuantumClub/map-frontend#1]
Flutter sopports the following build targets:
- Android
- IOS
- Linux
- macos
- Web

Which ones should we target? Maybe only mobile for v1 or all of them?

**Comment by Lemonatix** [comment]
I would think mobile first as well. So iOS and Android. We discussed about web, but we came to the conclusion, that it would be a but harder to implement. Android and iOS satisfies the usage for us all for v1 for sure.
